version: '3.7'

services:
  dockerservice:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./package.json:/opt/package.json
      - notused:/opt/app/node_modules
    ports:
        - "49160:8080"      
    environment:
      - NODE_ENV=development
      - PORT=8000
      - HOST=0.0.0.0
volumes:
  notused:
  dynamodb_data:
